### ISSUE TITLE
Create an intent (or tasker plugin) to start and stop scanning automatically

### ISSUE THREAD

**Issue by Hugo14** [mozilla/MozStumbler#952] opened 2014-10-08 09:09 UTC
It would be great if MozStumbler could receive an intent that would automatically start or stop the scanning. This way automation apps, like Tasker, could interact with MozStumbler and start and stop it when adequate. It's also possible to create a Tasker plugin, but an Intent would allow any application to interact with MozStumbler.

For example, I could automatically turn MozStumbler on everytime I get into the car and stop once I get out. This way without even having to make an effort I would be helping the project. Im sure other people could find other interesting uses and coding such an intent should be relatively easy.

**Comment by Djfe** [comment] 2014-10-10 00:51
this is a duplicate of #471 
@garvankeeley pls close this issue ;)

**Closed as completed** 2014-10-10 01:36 UTC
Labels: enhancement
