### ISSUE TITLE
Add to map layer with points

### ISSUE THREAD

**Issue by CupIvan** [mozilla/MozStumbler#397] opened 2014-02-11 13:41 UTC
Like in website: https://location.services.mozilla.com/map

After that, users will can view areas without data more quickly

**Comment by Djfe** [comment] 2014-02-11 16:09
belongs to #336

will be integrated some day ;)

**Comment by tamcap** [comment] 2014-02-11 21:15
It is actually very simple to implement as-is, however, due to coverage map issues (see #336, ichnaea discussions and [bugzilla bug 961429](https://bugzilla.mozilla.org/show_bug.cgi?id=961429)), it probably ~~won't become a mainstream feature for now~~ might become a feature.

**Comment by Djfe** [comment] 2014-02-11 23:36
it is not easy to implement as it needs the internal database (which seems to take a long time to develop...) to display the areas you have scanned already (without fuzzy and a data connection)

as you said it doesn't make sense to display covered areas only fuzzy (if you scanned them)

**Comment by tamcap** [comment] 2014-02-11 23:39
@Djfe - displaying current coverage has just been implemented. So that's done. However, the detail level of coverage is a different story, and this one is a source of many debates.

Implementing the database for local storage would be fairly easy. The problem is rendering 10000 locations and not killing your phone at the same time. Moreover, the online coverage map is still being debated and adjusted - thus I am guessing not much is being done re: local storage & display - as it might be superfluous in the near future, or require significant changes.

**Comment by cpeterso** [comment] 2014-02-12 01:16
Fixed by #399.

**Closed as completed by cpeterso** 2014-02-12 01:16 UTC

**Comment by gpoo** [comment] 2014-02-16 20:21
@tamcap One approach would be show _my_ last 100-200 points (therefore, the ones that should be nearby). When I am commuting I don't care about the points 6 kms away, but when I am walking and see myself with time to do some stumbling, I would like to know where I havet been that day to walk to the places I haven't been yet (in the day or session).
