### ISSUE TITLE
KML Reports File always empty

### ISSUE THREAD

**Issue by hbogner** [mozilla/MozStumbler#1537] opened 2015-03-04 19:43 UTC
Android 4.4.4 Cyanogen OS version 11.0-XNPH05Q
Android 4.4.2 Cyanogen OS version 11-20140321
Mozilla Stumbler version 1.7.2 from F-Droid
Mozilla Stumbler version 1.5.2 from F-Droid
And even versions before that.

I never managed to get anything in KML file, all I get is an empty file named by date an time:
obs-1-date-04-03-2015-20:34.kml
Size of file: 6B

**Comment by garvankeeley** [comment] 2015-03-04 19:56
I use this feature heavily, other than being not user-friendly, I haven't had any problems with it. We do have a 3 KML bugs filed in the last week that I'll try fix ASAP, but none would explain this.

According to the file name, and your description, the app has no observation points. Maybe it is a memory issue, I don't usually export thousands of points. How many observations (roughly) are you trying to export when this happens?

**Comment by garvankeeley** [comment] 2015-03-04 19:57
BTW, 1.7.4 has a KML fix that _might_ fix this bug.

**Comment by hbogner** [comment] 2015-03-04 20:01
This happens every time, from the time I started using the app for the first time.
When I try to export 1 point up to 3000 points.
On 2 phones. Never managed to export anything but the empty file.
Both phones running CM11.

**Comment by Djfe** [comment] 2015-03-04 20:07
Are you trying to export after you uploaded your reports?

**Comment by garvankeeley** [comment] 2015-03-04 20:09
As long as the dots are visible on the map view, KML will export them. It doesn't export from previous stumbling sessions. It is essentially a map view point export, for what is currently visible.

**Comment by hbogner** [comment] 2015-03-04 20:19
Was trying, before and after. Gave up after 20 unsuccessfull test.
Maybe it's a problem with CM.

**Comment by crankycoder** [comment] 2015-03-04 20:20
@hbogner can you file a bug in the settings?  Maybe I can see something odd in your device configuration.

**Comment by hbogner** [comment] 2015-03-04 20:30
Sent it.

**Comment by crankycoder** [comment] 2015-03-04 21:13
Hmm. Looks like you're on a OnePlus device. I have the same phone and it's working for me on 1.7.4.  

I noticed a bug in 1.7.3 where saving the KML would spin forever - seemingly in a deadlock, but that seems to not happen in 1.7.4 for me. 

F-Droid should get 1.7.4 shortly they merged 1.7.4 last night: https://gitlab.com/fdroid/fdroiddata/merge_requests/601

**Comment by hbogner** [comment] 2015-03-04 21:22
Yes, OnePlus One, and older one is Samsung Galaxy S+ I9001.
Have problems with both. Will submit log from SGS+ tomorrow.

**Comment by hbogner** [comment] 2015-03-06 22:44
Filed a bug report from Samsung Galaxy S+ I9001 yesterday. On it i get the message about creating KML file but there is no file. On OnePlus I at least get an empty file :D

**Comment by sshvetsov** [comment] 2015-03-13 14:59
Having the same problem on my Nexus 5 (stock 5.0.1) and Galaxy Nexus (CM 11-20141115-M12, 4.4.4). Gonna file bug from each device.

Forgot to mention, using v1.7.7 on both.

**Comment by hbogner** [comment] 2015-03-17 11:04
Using 1.7.7 from F-Droid.
Still empty KML.

**Comment by crankycoder** [comment] 2015-03-17 13:58
@hbogner @sshvetsov are you trying to generate KML while you are stumbling?  That developer option is only meant to export in-memory observation data to KML. It does not retrospectively go back and transform all the collection data to KML.

**Comment by crankycoder** [comment] 2015-03-17 15:56
@sshvetsov filed a bug report with steps to reproduce, but I get reports on mine:

Steps from app filed bug:
- Collect data 
- see it on the map 
- go to settings, Developer, click Save KML File 
- click cancel, when offered to share 
- go to sdcard/Android/data/org.Mozilla.mozstumbler/files/ 
- the kml file is only 6 B and has no data in it

---

Turning on stumbling from my desk I get this:

![2015-03-17 11 52 26](https://cloud.githubusercontent.com/assets/4829/6691370/92a00208-cc9c-11e4-8d23-3c09fc984563.png)

![2015-03-17 11 52 41](https://cloud.githubusercontent.com/assets/4829/6691349/78122e48-cc9c-11e4-99d4-e13b46a6112d.png)

**Comment by sshvetsov** [comment] 2015-03-17 16:30
Here are my screens from today:
![screenshot_2015-03-17-23-10-14](https://cloud.githubusercontent.com/assets/2501176/6692130/7256ec80-ccfd-11e4-9e29-89bb14d75f70.jpg)
![screenshot_2015-03-17-23-10-25](https://cloud.githubusercontent.com/assets/2501176/6692131/7257f6b6-ccfd-11e4-9d8f-9863008c935e.jpg)
![screenshot_2015-03-17-23-10-35](https://cloud.githubusercontent.com/assets/2501176/6692132/725ad46c-ccfd-11e4-9206-2ea9ca8d665e.jpg)
![screenshot_2015-03-17-23-10-40](https://cloud.githubusercontent.com/assets/2501176/6692134/72606e18-ccfd-11e4-877b-161a4b09db94.jpg)
![screenshot_2015-03-17-23-10-45](https://cloud.githubusercontent.com/assets/2501176/6692133/725ff690-ccfd-11e4-9064-7d20ba6ef70a.jpg)
![screenshot_2015-03-17-23-11-14](https://cloud.githubusercontent.com/assets/2501176/6692135/72646ec8-ccfd-11e4-8e7b-2f4000e4127d.jpg)
![screenshot_2015-03-17-23-11-29](https://cloud.githubusercontent.com/assets/2501176/6692136/728d7a3e-ccfd-11e4-95c3-40da012e476c.jpg)

**Comment by hbogner** [comment] 2015-03-17 20:49
@crankycoder  I do the same procedure as @sshvetsov and get the same results as him.
I can produce the same screenshots as him, if you like.

**Comment by crankycoder** [comment] 2015-03-17 20:52
It looks like you've turned off stumbling. That will upload all records into Ichnaea and clear your memory buffers.  The KML option only dumps in-memory reports.

I think part of the problem is the wording of "Developer Options". Those are options which are not rigorously tested but @garvankeeley and I find those options useful enough that we want to expose them.

We should probably display a dialog warning users that the options in that screen are unstable.

@hbogner, @sshvetsov can you try generating KML without stopping the stumbler?

**Comment by hbogner** [comment] 2015-03-17 21:49
Stumbling is turned off automatically when doing the KML export.
Just tested it, twice.
First time I left wifi on so the reports were sent automatically, stumbling was turned off automatically when doing the export.
Second time wifi was off to disable automatic upload and to keep them in the memory, stumbling was turned off automatically again.
In both cases there were created 6B empty files

**Comment by crankycoder** [comment] 2015-03-17 21:51
This is really puzzling.  I think you've got a OnePlus One right?  I have
the same device. I'll try to do a video capture of KML exports and we can
do a comparison of this.

**Comment by hbogner** [comment] 2015-03-17 21:58
Yes, OnePlus One and Samsung Galaxsy S+, and have the same issue with both of them.

**Comment by sshvetsov** [comment] 2015-03-18 01:13
Stumbling turns OFF for me automatically as well on stock Nexus 5 (5.1.0) and CM Galaxy Nexus. Still nothing is in the kml file.

**Comment by crankycoder** [comment] 2015-03-18 01:23
Huh. Ok, I just did a screencast and reproduced your problem with the
Playstore release of 1.7.7.

Then I did the same thing with a debug version of the github build and
everything worked.

So this looks like some kind of build related issue.  My favourite kind of
bug.  No wait. I mean my least favourite kind of bug.

Let me take a look at this.

**Comment by crankycoder** [comment] 2015-03-27 14:22
@sshvetsov, @hbogner can you try v1.7.10 ?  It's working for me using the github release of 1.7.10.  I'm going to blame #1594 if this works for you-  because we've changed nothing w.r.t KML output.

**Comment by garvankeeley** [comment] 2015-03-27 14:23
@crankycoder It didn't occur to me before, but this could have been another proguard bug in release builds.

**Comment by sshvetsov** [comment] 2015-03-29 10:54
@crankycoder Confirmed working on my Nexus 5 and Galaxy Nexus, I can now save my observations as KML file. Doing so still turns OFF the active stumbling when I press "Save KML File" button.

**Comment by hbogner** [comment] 2015-04-07 20:44
@crankycoder KML export, on 1.7.10 and 1.7.11, on OnePlus One, works fine now. It should work on older Samsung, will test it in next few days/weeks.
\o/

**Comment by crankycoder** [comment] 2015-04-07 20:46
I'm going to blame Proguard and terrible serialization over-optimisation for this one.  We changed nothing related to the KML output code.

**Closed as completed by crankycoder** 2015-04-07 20:46 UTC
Labels: bug
