### ISSUE TITLE
0.20.9 lacks of UI feedback when the capturing process is stopped/killed by the system

### ISSUE THREAD

**Issue by gpoo** [mozilla/MozStumbler#710] opened 2014-07-14 23:03 UTC
Maybe related to #708 

With 0.20.9, I could only see capturing feedback when I was on a bus, but none while walking, and some while I biking. By feeback/no feedback/some I mean:

Feedback:
- The GPS icon is shown in the notification bar, therefore, GPS is active and working.
- The "Location Scanned" counter increases as I am in movement.

No feeback:
- The GPS icon disappear after several seconds. I have not measured how long it takes, but it might be 30 seconds or so.
- If I press stop and start again, the GPS is activated again, but it has to do all the dancing to obtain the current position, and it gets deactivated after a while.
- The "Location Scanned" counter does not show any increment. It stays on 0 (zero).
- The MozStumbler icon is in the notification bar, therefore, it is active... but apparently no capturing anything that I could guess from the UI.

Some feedback:
- The GPS icon stays active (possibly because I was using another application that requires the GPS)
- The "Location Scanned" counter does not show any increment. It stays on 0 (zero).
- The MozStumbler icon is in the notification bar, therefore, it is active... but apparently no capturing anything that I could guess from the UI.

I noticed this after biking ~25 kms, that the UI only had in green the button I pressed to scan, but everything else with no change. 0 locations scanned. However, a day later the zone I was biking on appeared with dots in mozilla's map.  So, it seems it was scanning, but no providing any information.

I tried the usual sequence start/get the location/stop/start as in previous versions (given it never starts capturing the first time I activate it), but this time the trick did not work.

My guess was that MozStumbler was trying to save some battery by deactivating the GPS if I am not moving fast enough (like on a car).

I downgraded to 0.20.5, which works.

**Comment by gpoo** [comment] 2014-07-15 17:02
I will re-install it and I will get back to you once I have more information.  When I noticed it "wasn't tracking" anything I just got disappointed.  By when I noticed the map had my information, I had already switched back to 0.20.5.

Nevertheless, I don't think I am affected by the bug you mention because I have disabled Google-assisted locations.  It always takes time to get my position. Moreover, sometimes I don't get the position even with 10 visible satellites in use (according to MozStumbler).

**Comment by garvankeeley** [comment] 2014-07-16 20:29
Deleting my earlier comment, I thought that 0.20.5 allowed for fused locations, but I double-checked the code and it did not.
So, back to looking at just the output of the Log Activity, if you can post it here, thanks.

**Comment by gpoo** [comment] 2014-07-16 22:06
I installed 0.20.9, and I cannot reproduce the issue anymore.  I have tried with both walking and biking, and no apparent issue.

I am closing this issue (I don't see how can I label it as invalid, though).  If I get the problem again, I would re-open it and provide more information and log.  Thanks for your time!

**Comment by garvankeeley** [comment] 2014-07-16 22:06
Thanks!

**Comment by gpoo** [comment] 2014-07-17 18:53
I think I know what happened:

When there is no enough system resources, Android starts killing processes.  As 0.20.9 has separated the UI from the capturing process, when the later is killed, for the user still looks like it is capturing data (the icon in the notification area still is present).  The only way to figure out that it stopped, is to check the application regularly and/or check if the icon of the GPS is active.

I think the user should get some feedback when the process is killed.  I think the UI component notices it, because the notification area is still there, the counters are reset to zero, and the button of capturing switches from Stop to Start.

The feedback could be a dialog and/or removing the icon from the notification area (if it is doing nothing, then don't pretend the application is capturing data).

It was a coincidence that my phone was overloaded when I was walking or biking. Totally unrelated.

**Comment by garvankeeley** [comment] 2014-07-17 18:59
The app is single process, but if you are seeing this when resources are low, it does seem something is happening there that we aren't handling.

**Comment by gpoo** [comment] 2014-07-17 21:04
I can reproduce it easily by:
1. Start capturing
2. Open a heavy web-page, like https://location.services.mozilla.com/map (the default one, no zoom) in Firefox Beta.
3. Start zooming and panning with the hope of getting to my city with enough resolution to see the streets.

Because of lack of more resources (Nexus One + Cyanogenmod), sooner than later, it can't handle the tiles. Sometimes Android kills Firefox and other processes, sometimes not.  But MozStumbler will reset the counters to zero and stop capturing.

As a side note: the only purpose of looking the map is to know which streets -nearby- have not been visited. I am not interested in the dots, but a good-enough resolution map with what is missing. I usually plan ahead, but sometimes my memory is not that good... or sometimes I forget to remove the tab with the map.

**Comment by gpoo** [comment] 2014-07-30 23:39
I came to suspect that maybe the GPS process (or whatever that is) was killed, and MozStumbler did not noticed it.  That is, the icon on the notification bar still was there.

**Comment by garvankeeley** [comment] 2014-07-31 01:59
It will be interesting to see what happens when you try a build with this change:
https://github.com/mozilla/MozStumbler/pull/738
That work was done to reduce resource usage to a minimum.

**Comment by ioana-chiorean** [comment] 2014-08-12 10:45
I am seeing this while the battery drains and thge service is stopped: https://www.youtube.com/watch?v=z9D9MMJog3U 
The state from notification bar remains as if the process/service is still scanning but in the app the status is changed. 

This is critical as the users (including me) don't open so regularly the app for status

**Comment by naoliv** [comment] 2014-08-12 11:11
@ioana-chiorean the video is private and can't be viewed

**Comment by ioana-chiorean** [comment] 2014-08-12 12:08
@naoliv Sorry - it should have been unlisted not private. I've changed now the pref.

**Comment by garvankeeley** [comment] 2014-08-12 14:46
I see it too, filed as issue #761

**Comment by Djfe** [comment] 2014-10-10 01:10
@gpoo is this still an issue?

**Comment by crankycoder** [comment] 2014-10-10 01:12
This is a duplicate of #761 - the notification bar and the start/stop button were not hooked together properly.

Merged in #782.

**Closed as completed by crankycoder** 2014-10-10 01:12 UTC
