### ISSUE TITLE
Map crashes when Google Play Services is not installed

### ISSUE THREAD

**Issue by eggpi** [mozilla/MozStumbler#129] opened 2013-10-10 18:22 UTC
I'm running CyanogenMod 10.1.3 without Google's apps. Clicking the Locate Me button seems to cause a crash ("Unfortunately MozStumbler has stopped") on top of an error message telling my I don't have Google Play Services.

The stumbler does seem to start scanning, though, so it may be something crashing in the background. Logcat tells me that the exception on MapActivity.java:193 is caught.

**Comment by cpeterso** [comment] 2013-10-10 18:34
oops! Thanks for the bug report.

@guilherme-pg: I believe the log message about MapActivity.java:193 catching an exception is about a _different_ exception. Did you see any other exception stack traces in logcat?

**Comment by eggpi** [comment] 2013-10-11 10:42
Yes, sorry, there was another one right below it. For some reason the line numbers are not really interesting; they point to the declarations of the classes containing the methods in the stack rather than to the lines that are executing.

However, it's a NullPointerException that has MapActivity$GetGeolocationAndMapItTask.onPostExecute and then MapActivity.access$500 at the top of the stack, so it seems reasonable to assume setPositionAndMarker is crashing due to mMap being null.

I can test that hypothesis later today if it's not easy for you to do it :)

**Comment by eggpi** [comment] 2013-10-25 11:19
Hmm, for some reason this didn't really fix the problem for me. This time I got a RuntimeException when trying to call setContentView at MapActivity.onCreate. Catching that exception does prevent the crash for me, I'll have a patch later.

I also tried reverting your null pointer handling and applying my change, and that once again prevented the crash. So it looks like the actual fix does not involve the null pointer checks, sorry if I misled you.

**Comment by merike** [comment] 2013-10-28 20:04
I get the following with 0.7.0 when pressing Locate Me:
W/dalvikvm( 1965): VFY: unable to resolve virtual method 1625: Lorg/mozilla/mozstumbler/MapActivity;.getFragmentManager ()Landroid/app/FragmentManager;
D/dalvikvm( 1965): VFY: replacing opcode 0x6e at 0x0013
D/dalvikvm( 1965): VFY: dead code 0x0016-0057 in Lorg/mozilla/mozstumbler/MapActivity;.onCreate (Landroid/os/Bundle;)V
D/AndroidRuntime( 1965): Shutting down VM
W/dalvikvm( 1965): threadid=1: thread exiting with uncaught exception (group=0x40028a00)
E/AndroidRuntime( 1965): FATAL EXCEPTION: main
E/AndroidRuntime( 1965): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.mozstumbler/org.mozilla.mozstumbler.MapActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class fragment
E/AndroidRuntime( 1965):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
E/AndroidRuntime( 1965):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2797)
E/AndroidRuntime( 1965):        at android.app.ActivityThread.access$2300(ActivityThread.java:135)
E/AndroidRuntime( 1965):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
E/AndroidRuntime( 1965):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1965):        at android.os.Looper.loop(Looper.java:143)
E/AndroidRuntime( 1965):        at android.app.ActivityThread.main(ActivityThread.java:4914)
E/AndroidRuntime( 1965):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1965):        at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 1965):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
E/AndroidRuntime( 1965):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime( 1965):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1965): Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class fragment
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:576)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
E/AndroidRuntime( 1965):        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:207)
E/AndroidRuntime( 1965):        at android.app.Activity.setContentView(Activity.java:1654)
E/AndroidRuntime( 1965):        at org.mozilla.mozstumbler.MapActivity.onCreate(MapActivity.java:86)
E/AndroidRuntime( 1965):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1065)
E/AndroidRuntime( 1965):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2745)
E/AndroidRuntime( 1965):        ... 11 more
E/AndroidRuntime( 1965): Caused by: java.lang.ClassNotFoundException: android.view.fragment in loader dalvik.system.PathClassLoader[/data/app/org.mozilla.mozstumbler-2.apk]
E/AndroidRuntime( 1965):        at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
E/AndroidRuntime( 1965):        at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
E/AndroidRuntime( 1965):        at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.createView(LayoutInflater.java:466)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:544)
E/AndroidRuntime( 1965):        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
E/AndroidRuntime( 1965):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
E/AndroidRuntime( 1965):        ... 20 more
W/ActivityManager(  104):   Force finishing activity org.mozilla.mozstumbler/.MapActivity
W/ActivityManager(  104):   Force finishing activity org.mozilla.mozstumbler/.MainActivity

**Comment by cpeterso** [comment] 2013-10-29 05:18
@merike: oops! It looks like Android's `android.app.FragmentManager` API is only available in Honeycomb or later. I'll have to investigate if there is a workaround for Gingerbread. I created a new bug report #144 for this Gingerbread problem.

**Comment by eggpi** [comment] 2013-10-29 11:01
So this is interesting. When I build latest master and install it myself (`gradle installDebug`), I get the same exception as @merike, which is in this gist: https://gist.github.com/anonymous/6b3ab332de959d76c342

However, if I install 0.7.1 from the releases page (which should be the same as the one I installed), I get the expected mMap == null problem, which is treated successfully, so no crash: https://gist.github.com/guilherme-pg/176a17a47a22347197df

@cpeterso I expect my latest PR to fix the former problem, while the null mMap problem seems to have been already resolved. But I don't really know how I'm only able to cause it when I build it myself...

**Comment by cpeterso** [comment] 2013-10-29 16:23
`ClassNotFoundException: Didn't find class "com.google.android.gms.maps.MapFragment"`

@guilherme-pg: On your dev machine, have you installed the "Google Play Services" and "Google Repository" extra libraries installed using the Android SDK Manager? You probably did (because I would expect the gradle build to fail). Have you tried `gradle assembleRelease ; adb install -r build/apk/MozStumbler-release-unsigned.apk`?

Also, your local build's won't show the map unless you register a (free) Google API key. Our GitHub releases use my Google API key. <:)

**Comment by merike** [comment] 2013-10-29 19:19
I'm on Froyo so workarounds for Gingerbread should probably be applied to that as well if they don't apply automatically without extra effort :)

**Comment by cpeterso** [comment] 2013-10-29 20:48
@merike: The workaround I added will cover both Gingerbread and Froyo. :)

**Comment by marco-c** [comment] 2013-11-05 17:56
mozStumbler could be listed on F-Droid if it was possible to build it without Google Maps and Google Play Services (see https://f-droid.org/forums/topic/mozstumbler/)

**Comment by cpeterso** [comment] 2013-11-05 20:15
@marco-c: we are investigating alternative map solutions so we would not need Google Maps API.

**Comment by dougt** [comment] 2013-11-23 02:15
Issue 209 is investigating using mapbox instead.

**Comment by dougt** [comment] 2013-12-27 06:52
We're using mapbox.  closing.

**Closed as completed by dougt** 2013-12-27 06:52 UTC
Labels: bug
