### ISSUE TITLE
Unfortunately, MozStumbler has stopped. OK

### ISSUE THREAD

**Issue by folgorante** [mozilla/MozStumbler#598] opened 2014-05-19 12:58 UTC
After less than a minute MozStumbler has been started. The message "Unfortunately, MozStumbler has stopped. OK" appears. Nexus 7, Andriod 4.4.2. This happens since past saturday. The app was then uninstalled and then reinstalled, but the problem persists.

**Comment by Valeryan24** [comment] 2014-05-19 13:03
Did you just restart your phone and is MozStumbler stored on SD Card ? It happens to me until SD is finally mounted.

**Comment by folgorante** [comment] 2014-05-19 13:16
There is no SD Card slot in Nexus 7. The tablet was switched down an then restarted and MozStumbler reinstalled from scratch.

**Comment by Djfe** [comment] 2014-05-19 14:49
An adb log might be helpful to see why it has crashed.
Has this issue been introduced with 0.20.3 or an earlier version? (EDIT: You said it happens since Saturday, but I don't know whether you have updated from 19 or an earlier version)

Is this issue independed of scanning or does it happen one minute after scanning has started?

**Comment by folgorante** [comment] 2014-05-19 18:35
What I remember is that friday afternoon (Europe) it worked, then saturday monday it exploded the first time, and _after_ that it said there was an upgrade available. I promptly installed it (0.20.3). That didn't solve as it crashed again and again. Probably the first not working version was 0.20.2 or perhaps 0.20.1.

Now I'm able to reproduce the event: Disabling location or going indoor MozStumbler can be started with "Start Scanning".  When the GPS position is acquired going outdoor or enabling location from the android menu MozStumbler crashes immediately.

For the adb log I must study how to do it.

**Comment by folgorante** [comment] 2014-05-19 18:43
Update: I uninstalled 0.20.3, downgraded to 0.20.2 and it crashed. Then unistalled 0.20.2, downgraded to 0.19.0 and it's working.

**Comment by Djfe** [comment] 2014-05-19 20:25
0.20.1 and 0.20.2 were kinda failed releases they used a wrong signature so that you couldn't update correctly to them
the latest version was 0.20.0, it has been released on thursday, but there was a bug in it so that there was a bugfix release on saturday, which kinda failed because of the wrong signing key

so it depends on when you updated

it would be interesting to hear whether 0.20.0 works:
https://github.com/mozilla/MozStumbler/releases/tag/v0.20.0

if it doesn't work then the issue has been introduced with 0.20.0 else it has been introduced with 0.20.1/2/3, because as you stated: 0.19.0 worked fine for you.

**extraction from the changelog of 0.20.0**->possible causes:

```
Use LocalBroadcastManager for wifi,cell, gps broadcast
Switching to single process
Update osmdroid-android to 4.1
Remove obsolete looper and alarm
Fix BadTokenException from UpdateDialog
```

**Comment by tamcap** [comment] 2014-05-19 20:27
The 0.20 was a BIG change in many areas at the same time. Please be
understanding when we work out the kinks.

**Comment by folgorante** [comment] 2014-05-19 21:26
I couldn't try 0.20.0 because the .apk file is not available, and I don't know how to compile from source.

**Comment by garvankeeley** [comment] 2014-05-19 21:34
Could you try install a logcat viewer and post the output after MozStumbler stops?
In the store, there are ones such as
https://play.google.com/store/apps/details?id=yuku.logviewer
Or a direct APK
https://code.google.com/p/android-log-collector

**Comment by folgorante** [comment] 2014-05-19 22:10
Upgraded to 0.20.3 and launched.

After the GPS signal is acquired MozStumbler displays "Unfortunately, MozStumbler has stopped. OK". 

In Settings -> Apps -> RUNNING  I see "MozStumbler 1 process and 1 service". So the process is still alive, but if I open it the "Start Scanning" button is showed again.

Just after MozStumbler 0.20.3 stopped I run logcat, this is the result:

device.txt
build.board=deb
build.brand=google
build.cpu_abi=armeabi-v7a
build.device=deb
build.display=KOT49H
build.fingerprint=google/razorg/deb:4.4.2/KOT49H/937116:user/release-keys
build.host=wped11.hot.corp.google.com
build.id=KOT49H
build.manufacturer=asus
build.model=Nexus 7
build.product=razorg
build.tags=release-keys
build.time=1386200391000
build.type=user
build.user=android-build
version.codename=REL
version.incremental=937116
version.release=4.4.2
version.sdk_int=19

logcat.txt
2014-05-19 21:45:45.557 I 18450/Adreno-EGL: <qeglDrvAPI_eglInitialize:320>: EGL 1.4 QUALCOMM Build: I0404c4692afb8623f95c43aeb6d5e13ed4b30ddbDate: 11/06/13
2014-05-19 21:45:45.587 D 18450/OpenGLRenderer: Enabling debug mode 0
2014-05-19 21:45:48.340 D 18450/dalvikvm: GC_CONCURRENT freed 137K, 2% free 9303K/9472K, paused 2ms+2ms, total 37ms
2014-05-19 21:46:16.437 D 18450/dalvikvm: GC_CONCURRENT freed 100K, 2% free 9660K/9792K, paused 3ms+10ms, total 45ms
2014-05-19 21:50:04.489 D 18450/dalvikvm: GC_CONCURRENT freed 137K, 2% free 9992K/10160K, paused 3ms+2ms, total 18ms

**Comment by Djfe** [comment] 2014-05-19 23:03
you need to run the logcat while using MozStumbler not afterwards ;) :
Start logcat
start scanning in mozstumbler
_crash_
switch to logcat
stop logcat
upload the log file created here/write it down
should be more than just a few lines

tutorial how to logcat on xda:
http://forum.xda-developers.com/showthread.php?t=1726238

**Comment by folgorante** [comment] 2014-05-20 08:51
Reading the documentation I've found that logcat application don't run in the background, they get information collected in a system log, so running them just after the event should be correct (as per Yuku Log Viewer instructions).
But on the newer versions of Android root privilege is required to read the logs of other applications. I'll see what to do about that.

**Comment by folgorante** [comment] 2014-05-20 15:10
- started MozStumbler
- activated location
- pressed "Start Scanning" 
- adb logcat
- MozStumbler has stopped

here is a copy of adb logcat output:
https://drive.google.com/file/d/0ByTd8I9zHhJ4aDhCMy1KTlAySjA/edit?usp=sharing

**Comment by garvankeeley** [comment] 2014-05-20 18:03
Thanks for the report! It has the key piece we needed:

E/AndroidRuntime( 8802): FATAL EXCEPTION: main
E/AndroidRuntime( 8802): Process: org.mozilla.mozstumbler, PID: 8802
E/AndroidRuntime( 8802): android.database.sqlite.SQLiteConstraintException: reports.radio may not be NULL (code 19)
E/AndroidRuntime( 8802): at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)

**Comment by garvankeeley** [comment] 2014-05-20 20:07
In Reporter.java:167, we do 
 if (mPhoneType == TelephonyManager.PHONE_TYPE_GSM ||
            mPhoneType == TelephonyManager.PHONE_TYPE_CDMA) {
..
}

If mPhoneType is not one of these values, then the radio column is left null, and we have a non-null constraint on the db definition for that column. Could be fixed simply by allowing null. Could someone who knows the history of how this came to be take a look?

**Comment by Djfe** [comment] 2014-05-20 20:13
seems to be related:
https://groups.google.com/forum/#!topic/android-developers/bILNC6t682k

**Comment by Djfe** [comment] 2014-05-20 20:17
another thread:
https://code.google.com/p/android/issues/detail?id=53518

The issue is device dependend.

EDIT:
mozilla/ichnaea#202 -> I think @hannosch wants to keep consistency -> each entry is supposed to have a radio type (if I'm not confounding this...)

**Comment by eggpi** [comment] 2014-05-20 20:23
It may be worth it to investigate why this device's radio type is being reported as NONE, but I think the best course of action for this issue is to just allow Reports.RADIO to be null in the database, or just normalize it to "" in the reporter. In general, as discussed with @hannosch over IRC, we want to ignore cell scans when the phone type is not GSM or CDMA.

**Comment by Djfe** [comment] 2014-05-20 20:29
is it worth it to take guesses on the radio type used by taking a look at the cells lat/lon values?
mozilla/ichnaea#16

**Comment by eggpi** [comment] 2014-05-21 14:38
I don't think so at this point, unless we come across a significant number of other devices in the same situation as @folgorante 's. Perhaps we should have some stats on that, which could be either captured from the stumbler app, or simply a count of how many reports arrive at the server with no cell data.

**Comment by folgorante** [comment] 2014-05-21 15:06
There are a lot of devices which can't do phone calls out here. Almost all the tablets, for example. And for sure also PHONE_TYPE_SIP won't give phone cell information.

EDIT: There should be many devices which can't do phone calls, but can connect to cellular networks for data connection only. So is it useful at all to call the method getPhoneType () ?

**Comment by eggpi** [comment] 2014-05-21 16:07
Yes, by "same situation" I meant devices whose "phone type" is NONE for whatever reason, but are otherwise capable of scanning. I don't think we should try to guess their type unless they turn out to be numerous. I don't think they are (see below about tablets with data connections), but I'll be glad to revisit this if I turn out to be wrong.

You do have a good point about devices that connect to cellular networks but can't make calls. I think we do want to support those. However, a quick research suggests that for many of those devices [[1](https://stackoverflow.com/questions/5196833/android-device-phone-call-ability),[2](https://stackoverflow.com/questions/4403687/how-can-i-tell-that-samsung-galaxy-tab-cannot-place-phone-calls)] the value of `getPhoneType()` is still CDMA or GSM, and not NONE. Again, if that's not the case for the majority of devices of that type, we can work around it.

And of course, for tablets without data connection or PHONE_TYPE_SIP we don't want to (and can't) scan cell data, but WiFi scanning will still work.

**Comment by folgorante** [comment] 2014-05-21 17:49
I own a google Nexus 7 with GSM/LTE capability. From what I have seen above it returns PHONE_TYPE_NONE. It's not able to do phone calls, but receives SMS and connects to GSM/LTE networks. If you like I can use it as a testbed.

**Comment by garvankeeley** [comment] 2014-05-28 01:28
Fixed by the commits on this issue, closing.

**Closed as completed by garvankeeley** 2014-05-28 01:28 UTC
