### ISSUE TITLE
Add Offline Geolocation with cellids

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/MozStumbler#841] opened 2014-09-14 19:28 UTC
Is it possible to add a "Offline Geolocation" with cellids?
Maybe you can select your mcc and mnc in mozstumbler and download the data (MLS export) only from this provider.
This could be useful 
- if data connection is not possbile because mobile reception is too bad
- if i am in foreign countries and roaming 
- if the data volume is consumed
- to reduce the requests to the api

**Comment by Djfe** [comment] 2015-02-28 21:02
you can use the following backend for microg-nlp:
https://github.com/n76/Local-GSM-Backend

it does exactly what you want and even includes stumbling without any service.

If you want the same for MLS but with online requests you can use:
https://github.com/microg/IchnaeaNlpBackend

Both apps are found on F-Droid, too.

You need the main service though (it can either replace the Google Geolocation service app (2 versions for different android versions) or you use xposed and the respective module for it):
https://github.com/microg/android_packages_apps_UnifiedNlp

**Comment by crankycoder** [comment] 2015-03-17 18:32
Duplicate of #1578

**Closed as completed by crankycoder** 2015-03-17 18:32 UTC
