### ISSUE TITLE
I see a different map at times

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1178] opened 2014-10-31 19:08 UTC
Sometimes I see a different map, from usual (rarely and only for a few seconds).
![2014-10-30 09 10 24](https://cloud.githubusercontent.com/assets/5685512/4867006/3d481f7e-6131-11e4-817f-f16399326777.png)
I'm using the GitHub version, and normally I get this map:
![2014-10-30 09 10 50](https://cloud.githubusercontent.com/assets/5685512/4867014/48b2783c-6131-11e4-91ad-fb6cf62a6961.png)

**Comment by cpeterso** [comment] 2014-10-31 22:39
Are these screenshots from the same build? I think the first screenshot shows OSM map tiles and the second MapBox tiles. Have you ever tested installed a MozStumbler build from F-Droid or your own local build on the same device? Non-Mozilla builds don't have a MapBox license key, so they fallback to OSM map tiles, which may have become cached in osmdroid's shared tile cache on the sdcard.

**Comment by Djfe** [comment] 2014-10-31 22:43
yes, I had but that was way back
I have deleted the OSMdroid folder since it isn't needed anymore for Mozilla Stumbler (it uses the app cache now and a different tile caching method)
so the issue might have vanished now, the tiles were only visible for a few seconds where I had no internet connection, yet (I got lucky to take a screenshot)

will close this until it happens again

**Comment by crankycoder** [comment] 2014-11-03 15:07
This is almost certainly a bug in osmdroid.

**Comment by crankycoder** [comment] 2014-11-03 15:10
I forked and started hacking on the BasicTileProvider and renamed it to BetterTileProvider.

While doing so, I commented on bugs I found while refactoring and cleaning up the code.

The problem of the wrong map is because of a too many constructors, and one in particular which passes in a default tile source:

https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/java/org/mozilla/osmdroid/tileprovider/BetterTileProvider.java#L25

That constant gives you Mapnik tiles as per:

https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/java/org/mozilla/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L100

I've commented some more about the problem with default TileSource.  

https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/java/org/mozilla/osmdroid/tileprovider/BetterTileProvider.java#L46

The fix to this is - get rid of the multiple constructors to BetterTileProvider, especially the one where we pass in a default tile source in.

The problem is that this is quite difficult.  osmdroid does not provide many clean interfaces and collapsing the class hierachy is hard as calling instances usually call through an abstract base class instead of an interface definition.  This means that refactoring this properly involves understanding how each of the super classes is involved.

**Comment by Djfe** [comment] 2014-11-03 16:26
So you are gonna basically almost rewriting the whole code of osm?
Wow!
you could improve the source by committing your changes so that those bugs get fixed in the original version, too :D

**Comment by garvankeeley** [comment] 2014-11-06 15:36
I think we should sit on this bug for now:
- I am assuming this is an extremely rare report
- It is harmless
- OSMDroid always has a fallback to this map style, I think changing this behaviour will introduce a different set of bugs.

**Comment by crankycoder** [comment] 2014-11-07 01:43
Agreed.  There are lots of other more pressing issues like power management.  

Considering that this is a fairly harmless bug,  I say we close this bug with a won't fix for now and mark it as a known issue referencing the closed bug.

**Closed as completed** 2015-03-17 19:56 UTC
