### ISSUE TITLE
Geofencing changes

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#558] opened 2014-04-28 14:26 UTC
Could it be possible to
1. Get multiple geofence locations
2. Allow user selectable geofencing distances

**Comment by Djfe** [comment] 2014-04-30 19:11
opened up an issue with the same suggestions two months ago :+1:
#424

**Comment by crankycoder** [comment] 2014-09-03 14:02
Closing as duplicate of #424.

**Closed as completed by crankycoder** 2014-09-03 14:02 UTC
