### ISSUE TITLE
Change user agent header to include some device info

### ISSUE THREAD

**Issue by hannosch** [mozilla/MozStumbler#287] opened 2014-01-12 17:14 UTC
We changed the user agent header for all server requests to include the MozStumbler version a while back. The code is at https://github.com/mozilla/MozStumbler/blob/master/src/org/mozilla/mozstumbler/Reporter.java#L197

This means we only get a string like `MozStumbler/0.8.3` on the server side. For older clients and the Fennec code we get a string like `"Dalvik/1.6.0 (Linux; U; Android 4.3; GT-N7100 Build/JSS15J)"`.

I think it would be interesting to retain at least the Android version in the user agent. If there's an easy way to distinguish "official Android" from other distributions like CyanogenMod that would be interesting as well.

I'd like to have that information, so we can make data-based decisions on questions like: What minimum version of Android should we support. Or: If we require Google Play services, how much of our user base does that affect.

**Comment by cpeterso** [comment] 2014-01-12 18:56
What information would be useful: MozStumbler version, Android OS version, and Google Play Services version (if installed)?

**Comment by Djfe** [comment] 2014-01-27 15:18
maybe also what the device supports regarding wifi and mobile data
(b/g/n/ac wifi, edge/gprs/UMTS/hsdpa/lte)

which language is used (system-wide) -> is this app translated into the most common languages
->can we engage more users to translate the app (on crowdin.net for example)

**Comment by jrconlin** [comment] 2014-01-27 15:54
I'd caution against gathering too much information, as it is not The Mozilla Way. I'd limit it to the very minimum of info that you'd need. (MozStumbler version, OS version, and maybe if play is available). 

It's far too easy to gather all the data possible because we might be able to use it. The problem is that the app is already collection time and location information (which is a fairly good indicator for language), and cell towers which could also be analyzed for data type. If there has to be some heavy lifting done on the back end, or holes in the data, so be it. I'd rather that than have detailed information recorded about users that less savory folk could abuse.

**Comment by Djfe** [comment] 2014-01-27 16:30
well, the information isn't needed per se, yes
but as you said we can guess it from all the other informations gathered
what do you think about a setting to make the user decide
so that he allows Mozilla the "anonymous" (gps positions aren't connected to the user) gathering of such informations for better statistics (this option should be disabled by default of course and the user should be able to see which information is gathered, the informations should be as few as possible as you said)

even if you think it's too much information, the user should be aware if the app sends the informations cpeterso posted about (mozstumbler, OS and playstore version)

**Comment by jrconlin** [comment] 2014-01-27 17:04
User opt-in helps, so long as we're very clear about what data we collect and how we plan on using it. People tend to be upset when they're surprised about how personally identifying data is used. 

(See https://twitter.com/TheBakeryLDN/status/427531934294880256/photo/1 )

**Comment by Djfe** [comment] 2014-01-27 21:03
quite understandable, in such a case...
at least those 3 little things are completely impersonal and as a matter of fact quite helpful for the development, so I think even persons who post stuff similar to the linked one should be satisfied.
(you have convinced me :) )

**Comment by Djfe** [comment] 2014-08-06 20:53
device name and rom name could be useful as well,
if there are known bugs in specific roms/devices ichnaea could handle their data differently

**Comment by Djfe** [comment] 2014-10-10 00:40
@garvankeeley is this fixed now or do we need an opt-in for data collection still?
what about sending hardware specifications along with the android version?

**Comment by crankycoder** [comment] 2014-10-10 01:56
We added user-agents in #972 based on system defined http.useragent property

**Closed as completed by crankycoder** 2014-10-10 01:56 UTC
Labels: enhancement

**Comment by Djfe** [comment] 2014-10-10 02:07
Could you still answer my questions pls ;)
