### ISSUE TITLE
Interval based peroidic scanning

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#369] opened 2014-01-30 08:15 UTC
It would be nice to be able to set MozStumbler to periodic scanning where the app would automatically launch and scan at intervals set by the user. So maybe every half hour or so or hourly when GPS active.

**Comment by Djfe** [comment] 2014-03-13 22:51
Do you want to save battery by doing this?

The GPS needs to be online the whole time as it can take long to reestablish it.
You would "only" save power which would be normally caused by cell and wifi scans.

**Comment by meteficha** [comment] 2014-11-15 00:56
A variation on this theme would be using the Lollipop's job scheduling API.

**Comment by Djfe** [comment] 2014-11-15 18:53
the API level is too high, so i guess until someone else is interested in this and contributes commits for it that the feature won't be implemented by using the new API, since that would limit the use to newer/high-end devices (except play store edition devices)

this will probably be implemented without the new API first

**Comment by crankycoder** [comment] 2015-08-26 16:28
I think the intent here is to enable better low power stumbling, but it's unclear from the bug description.  

Strictly implementing an interval based scan would not give the GPS enough time to get a fix.  The primary power draw on the stumbler is the GPS itself.  

As we have passive stumbling contributed by @cascheberg in #1649 already, I think it makes more sense to have some more testing done around passive stumbling and then promote passive stumbling as a standard feature of the stumbler.

**Closed as completed by crankycoder** 2015-08-26 16:28 UTC
Labels: enhancement
