### ISSUE TITLE
MozStumbler-1.7.14 Build Error with Android Studio 1.5.1

### ISSUE THREAD

**Issue by raymondspame** [mozilla/MozStumbler#1743] opened 2016-01-12 13:39 UTC
I tried every possible solution which I could find from the internet and I installed every necessary SDK but the problem remains.

The error message is as below and the IDE log is attached. Did anyone encounter the same issue? 
1. Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly.
2. Error:(214, 0) No such property: bootClasspath for class: com.android.build.gradle.AppPlugin
   <a href="openFile:D:\OpencellId\Mozilla\MozStumbler-1.7.14\android\build.gradle">Open File</a>

[idea - MozillaStumbler.txt](https://github.com/mozilla/MozStumbler/files/87348/idea.-.MozillaStumbler.txt)

**Comment by crankycoder** [comment] 2016-01-12 16:23
Are you able to build at all from the command line?

**Comment by crankycoder** [comment] 2016-01-12 16:46
@raymondspame - did you follow the build instructions in the README.md file?  I just finished making very minor updates to the documentation, but I just tried building and running a debug build from a fresh git clone - and it worked for me.

<img width="1230" alt="leaderboardactivity_java_-_mozstumbler_-____dev_mozstumbler__and_mozstumbler-1_7_14_build_error_with_android_studio_1_5_1_ _issue__1743_ _mozilla_mozstumbler_and_1__bash" src="https://cloud.githubusercontent.com/assets/4829/12270004/0666d3a2-b922-11e5-927b-4cde199edaca.png">

**Comment by raymondspame** [comment] 2016-01-13 01:38
Thanks. Yes, I followed the instruction in the README.md file but the error displayed in the dialog box (as shown in the attached PNG). It seems something wrong with gradle project sync. As I am using Windows 10, could you let me know how to build from command line?

According to the log I provided, it even failed to import this gradle project.
2016-01-12 21:28:01,907 [  22721]   INFO - .BaseProjectImportErrorHandler - Failed to import Gradle project at 'D:\OpencellId\Mozilla\MozStumbler-1.7.14'

![mozstumbler-1 7 14_builderror](https://cloud.githubusercontent.com/assets/16607618/12282256/c7e4d744-b9d7-11e5-9e65-7df6074c44b6.png)

**Comment by crankycoder** [comment] 2016-01-13 18:01
The Module setting in your configuration looks to be wrong.  Can you change it from "MozStumbler-1.7.14" to "android" ?

The command line build just uses make and it really just invokes "./gradlew assembleGithubDebug"

I don't have a Windows machine readily availble - can you let me know if either AS or cmd line builds work for you?

**Comment by crankycoder** [comment] 2016-01-13 22:45
@raymondspame - I feel bad for doing this, but the build just changed again in the dev branch.

I just landed the leaderboard build flavor so 'make debug' will now issue "./gradlew assembleGithubLbdevDebug"

Can you give that a try?

**Comment by crankycoder** [comment] 2016-01-19 15:58
I can't reproduce this with the dev branch and we're cutting a production release shortly - so I'm closing this.

**Closed as completed by crankycoder** 2016-01-19 15:58 UTC
