### ISSUE TITLE
MapFragment metrics updates are 'laggy'

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1567] opened 2015-03-13 19:57 UTC
When toggling the stumbler from on to off and then back on again, the visible AP and cell numbers do not seem to bounce back to non-zero numbers quickly after #1563 landed.

**Comment by cascheberg** [comment] 2015-03-13 23:54
Could this be because of #1559? Because of that cell and wifi scans are only done after the first new GPS position report. In that case this is not a bug.

**Comment by crankycoder** [comment] 2015-03-14 16:51
It might be,  I haven't had a chance to back out both changes and then
bisect to determine the root cause.   The good news is that it's either the
single commit in #1559 or the final commit in the bindservice removal PR.

I'm also seeing the stumbler service stop running when the screen is off.
I'll post a screenshot tonight when I get a chance.

**Comment by cascheberg** [comment] 2015-03-15 13:38
Since you mentioned that the service stops running when the screen is off: with #1563 landed, when I minimize the app I see no indication of active GPS anymore. And it seems that GPS is actually stopped since it has to search for satellites very time I bring the app back to the foreground. Only the notification is still there.

**Comment by crankycoder** [comment] 2015-03-17 13:53
Thanks for noticing this. I've backed out the removal of `bindService` in #1572. That seems to make things better again.  The other commits in #1563 were related to decoupling the service pointer dependency and using Intents to message between the service and the client application.

My guess at this point is that with unbound services the Android VM is simply marking the stumbler service as garbage, stopping the thread until the app is woken back up.  I really have no way of verifying this as the AOSP code quickly hits the vendor layer which doesn't have source though.

**Closed as completed** 2015-03-17 14:28 UTC
