### ISSUE TITLE
MozStumbler - collecting data with no result

### ISSUE THREAD

**Issue by Moztmp** [mozilla/MozStumbler#736] opened 2014-07-29 09:01 UTC
Hello.

I've got problem with MozStumbler. I went to trip throught Balcans
(Romania, Bulgaria, Macedonia, Albania, Montenegro, Croatia...). I
collected about 200 000 measurements, I send it every day. Program says
it's all OK, but in ranking there is no progress for my accout. On
Sunday I reset program settings and I went to 550km trip throught Poland
and situations occurs again - no records on website... What can be
wrong?

Program says that I collected and send 414 255 measurements but ranking says only 259 342

**Comment by Djfe** [comment] 2014-07-29 21:02
Did you use your mobile network and roaming?
I think this got fixed already (issue was listed on the server's repo: mozilla/ichnaea#280 (edit: wrong ticket id))
The server accepts all send entries but doesn't notify the client whether he is deleting or keeping the entries
the issue was that the server deleted uploads from IPs that are outside of the country you are sending data from (-> you got a different IP because of roaming (from your home country))

@hannosch maybe you can explain this issue a little better than me

**Comment by Moztmp** [comment] 2014-07-30 06:31
Yes, I used roaming. But problem still ocurs in my home-country on my home-country IP... After reset settings to default and reinstalling MozStrumbler there is still a problem.

**Comment by Djfe** [comment] 2014-10-10 01:15
@crankycoder  not an issue anymore since the server-side ip checks got removed by hannosch again

**Comment by crankycoder** [comment] 2014-10-10 01:37
It's not clear that this bug has been resolved.  I've filed #979 to add a paranoid logging mode to assist with debugging these sorts of issues.

I'm going to close this though as I don't see a good way of reproducing the problem.  I'm pretty sure @Moztmp isn't going to go on another trip just to stumble data for us. :)

**Closed as completed by crankycoder** 2014-10-10 01:37 UTC

**Comment by Djfe** [comment] 2014-10-10 01:42
well but the issue here is pretty clear to me.
hannosch preferred geolocation(ip) over GPS, he introduced bounding boxes with you
but people on vacation get an ip from their provider which is not an ip from the country they are making vacation in -> the server just threw the uploaded observations away because they were uploaded from a different country
hannosch wanted to prevent spam, but he also prevented uploads that came in through vpns/tor/roaming
