### ISSUE TITLE
Frequent crashes and datalosses

### ISSUE THREAD

**Issue by da2x** [mozilla/MozStumbler#1790] opened 2016-05-09 12:31 UTC
Ever since the update that introduced the new login system, I’ve had troubles with crashes while out stumbling. Restarting the app shows now queued reports and the leaderboard confirms that the data is indeed lost. I don’t have any details or logs (don’t have logcat when out and about) other than this not being a problem prior to this update.

**Comment by lua86** [comment] 2016-05-09 12:33
Do you not have a terminal app in your phone?

**Comment by da2x** [comment] 2016-05-09 12:50
No, I’m running stock Android 6 on a Nexus 5X. The app worked just fine for hours on end before the update. Now it runs for ~40 minutes and silently crashes in the background while I’m stumbling. I’ve tried leaving my phone plugged in with logcat open but I can’t get it to crash on command in this situation.

**Comment by lua86** [comment] 2016-05-09 12:55
I have not upgraded in a while, since there seems to be some build problem with f-droid, so I cannot be sure about now, but there used to be an option allowing logging to file.

**Comment by da2x** [comment] 2016-05-09 13:09
Thanks for the hint. That file is only written when the app shuts down, so I expect a crash would prevent it from being written. It only contains stumbled data and I’m not seeing anything that would help identify the problem.

**Comment by crankycoder** [comment] 2016-05-09 16:14
@Aeyoun hrm..  can you enable crash logging in your build?  My guess is that this is somehow related to the way we're doing authentication against the leaderboard.  cc/ @jaredkerim

**Comment by da2x** [comment] 2016-05-09 16:41
@crankycoder, I do have the _enable crash reporting_ option checked but I haven’t seen any documentation on what happens when you enable it. I’m using the Google Play Store distributed build.

**Comment by crankycoder** [comment] 2016-05-10 17:05
Doh.  This is caused by #1786.

I'm cutting a v1.8.5 release today to address this.  I didn't realize how common that NPE crash was.

cc/ @jaredkerim - The leaderboard server is stalling still on uploads.  I've filed https://github.com/mozilla-services/location-leaderboard/issues/298 to track the bug.

@Aeyoun  - I'll close this bug when I push the v1.8.5 release to github.

**Comment by crankycoder** [comment] 2016-05-10 17:19
@Aeyoun  - try https://github.com/mozilla/MozStumbler/releases/tag/v1.8.5 and let us know if this fixes the problem.

**Closed as completed by crankycoder** 2016-05-10 17:19 UTC

**Comment by da2x** [comment] 2016-05-12 00:54
The latest update does indeed seem to have resolved the crashing for me. Thank you, @crankycoder.
