### ISSUE TITLE
Upload observations: infinite progress? disabled button?

### ISSUE THREAD

**Issue by goldfndr** [mozilla/MozStumbler#518] opened 2014-03-22 20:14 UTC
On my Froyo phone, in the Upload observations dialog, the progress spinner stays spinning, even when the In queue numbers reach zero, even after waiting a half hour after zeroes. Also, there's a disabled button ("Upload"); I've never seen it enabled, but perhaps that's due to having a nickname set and/or a sync account; is it not redundant if the "Upload observations" dialog is triggered?

I'm wondering if the progress could be changed to a horizontal progressbar, full/empty depending on what the In queue numbers started from (sum?). If the button is indeed never enabled and there are no future plans for it, removing it would allow a wider progressbar.

**Comment by tamcap** [comment] 2014-03-22 20:29
It's a bug within Android 2.x :-( I tried a few ways to make it work, and
couldn't figure out a way around it.

**Comment by Djfe** [comment] 2014-03-22 20:32
The Upload button is always disabled during the upload (has nothing to do with your nickname setting) -> you could say that it is not really needed as mozstumbler starts uploading as soon as you get a working connection and have enough entries in your queue. It is only needed for people that have a bad connection so that the upload files at times -> you can start it manually again.
The progressbar is a nice idea indeed.

@tamcap I have a question about this behaviour -> do you know what the issue is? doesn't android return an http code of 204?

**Comment by tamcap** [comment] 2014-03-24 08:03
It's just a graphics rendering bug. Uploading the actual observations seems to work ok. Not sure why the "Upload" button is disabled for @goldfndr ...

**Comment by Djfe** [comment] 2014-03-24 09:51
What do you think about a progress bar?

**Comment by Djfe** [comment] 2014-08-13 13:56
@garvankeeley you can close this, I think ;)

**Comment by garvankeeley** [comment] 2014-08-13 14:18
Agreed, this works now.

**Closed as completed by garvankeeley** 2014-08-13 14:18 UTC
