### ISSUE TITLE
Critical: Galaxy S5 motion detection not working, scanning never starts

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1322] opened 2014-12-03 20:32 UTC
Report on play store that this isn't working, after pausing scanning, the app fails to detect motion to start scanning again.

Not sure if it is a custom ROM or not. Would be good to have the log activity checked on startup to see if device has significant motion sensor or not. Also, what steps were taken to try wake the scanning?
(Chris hopefully you see this and can fill in the questions).

**Comment by crankycoder** [comment] 2014-12-03 20:47
On a related note - we should setup a google doc or an etherpad page with a list of all contributors and testers with the devices+ROM that they have on hand for testing.

**Comment by garvankeeley** [comment] 2014-12-05 06:30
We have to get to the bottom of this, I am hearing anecdotal reports from users that stumbling is "difficult" to start after pausing.
@cpeterso : did you confirm having problems on your Cyanogenmod 4.3 Nexus 4

**Comment by simonpoole** [comment] 2014-12-08 14:23
I can confirm the issue. Essentially even though no other apps have problems tracking the position at the same time (including such for which I'm the main dev) since version 1.5.2 mozstumbler seems to be essentially not working. Prior versions didn't exhibit this behaviour. 

While pausing seems to increase the issues, even freshly started the behaviour is erractic.

**Comment by garvankeeley** [comment] 2014-12-09 02:56
@simonpoole can you try 1.5.3 
https://github.com/mozilla/MozStumbler/releases/tag/v1.5.3

**Comment by simonpoole** [comment] 2014-12-09 21:39
@garvankeeley sorry, will test tomorrow,

**Comment by simonpoole** [comment] 2014-12-10 16:44
OK, the good news (1.5.3): behaviour is better in that there no unmotivated pauses and resulting hanging outside with good GPS reception, however it doesn't actually seem to pause at all even when clearly at rest. 

Bad news (repeatable): moving indoors with loss of GPS reception will, after a while lead to the app pausing recording and hanging (clear sign of this: GPS sat display in MozStumbler freezes and doesn't reflect actual available sats). 

 For completness sake, this is on a Galaxy S5 (G900F) with 4.4.2.

**Comment by garvankeeley** [comment] 2014-12-10 19:06
Any chance you can screenshot the Log screen when this happens?

My guess at the bug:
- with no GPS, then the app goes into 'paused' state.
- then if you keep moving at a constant rate, we don't get notification of a significant change in motion.

**Comment by simonpoole** [comment] 2014-12-11 11:36
![screenshot_2014-12-11-12-26-43](https://cloud.githubusercontent.com/assets/1011860/5393405/ccff1d00-8131-11e4-8d2d-bb74a7c6ad30.png)

This is from the end of testing, I believe I came in the door around 17:33, after roughly 2-3 minutes went upstairs where I had GPS reception again (verified with other app).

**Comment by garvankeeley** [comment] 2014-12-11 15:40
This log looks ok. To wake the scanning requires moving >50m in 2 minutes, do you know if you did that and it didn't wake up?

**Comment by simonpoole** [comment] 2014-12-11 16:07
Ok that explains a lot. If you are on foot and for example window shopping you might never start recording.

On 11. Dezember 2014 16:40:36 MEZ, Garvan Keeley notifications@github.com wrote:

> This log looks ok. To wake the scanning requires moving >50m in 2
> minutes, do you know if you did that and it didn't wake up?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/MozStumbler/issues/1322#issuecomment-66636979

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by garvankeeley** [comment] 2014-12-11 21:58
Hmm good point. 
- 1 after not moving 50m in 120s, app pauses
- 2 you continue to walk, app wakes, checks to see if location is indeed changing
- 3 after not moving 50m in 120s, app pauses
- repeat steps 2 and 3

Pausing is ok in this case, as it should immediately detect motion, and wake again.

**Comment by garvankeeley** [comment] 2014-12-12 22:41
#1350 Added a 'window shopping' test case "testSmallMovementThenPauseThenBigMovement()"

Seems to work ok, brief pauses will happen but scanning shouldn't be affected due to the regular wake ups from user's movements.

**Comment by kbrosnan** [comment] 2014-12-14 00:47
I can confirm that this fails even for large movements on a Galaxy S5. I traveled over 1km on foot without the stumbler re-enabling. The log is the same as simonpoole's.

Work around is killing mozstumbler using the Samsung task manager and restarting.

**Comment by grrrrr** [comment] 2014-12-15 19:02
I can add to this

Samsung Galaxy S4
CyanogenMod CM11 M11
Mozstumbler 1.5.4 and previously 1.5.3
Pause settings: 30m in 300s

Pause fails to resume while driving.   Set up was:  Driving for 8km, parked for 6 minutes, drive back the 8km.  MozStumbler never unpauses.  Had to toggle off and on when I noticed it was paused after approx 6km of driving.

**Comment by crankycoder** [comment] 2014-12-15 20:21
This is a list certainly because significant motion won't trigger in a car.

**Comment by garvankeeley** [comment] 2014-12-15 22:06
@crankycoder Any motion change in a car triggers it on my Nexus 5 (both with 4.4.4 and now L). Only constant speed in a car seems to not trigger it, in which case that is ok, as the GPS location would be changing, and thus we don't need the significant motion sensor.

**Comment by garvankeeley** [comment] 2014-12-15 22:14
@grrrrr @kbrosnan when this happens, can you use another app like GPS Status to see if you can get a GPS fix? It is possible that the GPS couldn't get a fix at that point, and therefore the app stayed paused. 

We should provide more feedback to the user that this is the current state, as this isn't paused due to not moving, this is paused due to no GPS fixes to tell the app a user is moving.

**Comment by garvankeeley** [comment] 2014-12-15 22:45
Can anyone having this problem post updated log activity screenshots? There is more debugging info that we added in 1.5.4 that may be present in the logs.

**Comment by kbrosnan** [comment] 2014-12-15 23:15
GPS seems to be working fine and even updates in the app. Will get a log with 1.5.4

![screenshot_2014-12-10-19-13-12](https://cloud.githubusercontent.com/assets/250273/5445913/2e59d246-846d-11e4-8d30-c51fa9dff7b0.png)

**Comment by kbrosnan** [comment] 2014-12-15 23:43
1.5.4 seems to be working correctly. 

![screenshot_2014-12-15-15-33-48](https://cloud.githubusercontent.com/assets/250273/5446256/0ef4206a-8471-11e4-9d7b-4ded2303b0ee.png)

**Comment by kbrosnan** [comment] 2014-12-23 09:51
Hm had it fail on my s5 again using the latest version. I was in a car, stopped to do an errand and it never resumed. City surface street speeds 25 mph/40 kph. Then transferred to a bike ride to the office. This is rather concerning as the s5 was my gold standard for gps accuracy. Any chance issue #1324 will help?

**Comment by garvankeeley** [comment] 2015-01-08 00:30
I am still stumped as to the cause of this. I have been trying to repro. I am trying to get my hands on an S5 and see if can get the problem to happen.
I don't think this is specific to that device, as there are now 2 more reports on the app store about this happening on HTC M8 and Android One devices.

I don't think #1324 is related.

One idea might be to have a setting to enable a more detailed paused message on the map view. This message could reveal the details of why the app is staying paused. The most likely case is that the GPS is not getting fixes. Or it might help reveal the bug, or more clues to the bug.

**Comment by Djfe** [comment] 2015-01-09 20:04
If it helps: my brother has the HTC one mini m7
I'm gonna test whether the issue is happening on that device as well and report further information tomorrow

**Comment by garvankeeley** [comment] 2015-01-09 20:53
Yes that helps.
I have yet to get my hands on a device that is suspected to have motion detection bugs. I have dozens of devices available for hands-on debugging, none of which match the specs of the bug reports.

**Comment by Djfe** [comment] 2015-01-11 21:34
mmh my younger brother doesn't allow me to test it with his device
maybe I can convince him the next time I'm at home ^^

**Comment by garvankeeley** [comment] 2015-01-14 20:31
Please try 1.5.5 on github and report your findings

**Comment by kbrosnan** [comment] 2015-01-26 16:52
1.6.1 this is still a problem

**Comment by garvankeeley** [comment] 2015-01-26 17:04
@kbrosnan in the new Power Saving Options screen, is motion detection on, and below that, your device is reported to have a 'significant motion sensor'?

Hmm, could it be that the GPS isn't getting a fix, and scanning pauses as a result? Can you keep an eye on the GPS sats (the fixed sats is the first number, 3 or more needed for a fix).

**Comment by kbrosnan** [comment] 2015-01-26 17:08
'Your device has a significant motion sensor' Yes motion detection was on. Yes it reports 0 SATs when I expect it to resume.

**Comment by garvankeeley** [comment] 2015-01-26 17:16
There is a 2 min window for GPS to become active*. In the event that it doesn't, scanning will pause, until more motion is detected, and it will try again. Does this correlate with what you see? 

*Assuming the user hasn't changed this in the Developer options screen

**Comment by kbrosnan** [comment] 2015-01-27 00:14
State 0: I stumbled for a few blocks, walking. Looks good. Waited two min for the lack of motion sensor to kick in. I have walked for about 5 min in this screenshot but stumbler does not seem to know this.

![screenshot_2015-01-26-13-59-15](https://cloud.githubusercontent.com/assets/250273/5910968/3955e92c-a575-11e4-884f-4e008d1af113.png)

State 1: a few seconds after the above screenshot I check in with Google maps. It seems to know what is north, south, east and west. More importantly where I am.

![screenshot_2015-01-26-13-59-34](https://cloud.githubusercontent.com/assets/250273/5911005/91432fb4-a575-11e4-8aa0-f7cb1c537c7a.png)

State 2: Back into stumbler. Hey it seems to know where I am now. Still motionless however.

![screenshot_2015-01-26-13-59-59](https://cloud.githubusercontent.com/assets/250273/5911039/f4ab81a0-a575-11e4-89e9-e9e8f22b22c9.png)

State 3: Swiped closed stumbler from the recent apps screen. Re-entered stumbler 0/0 satellites, not good. Still no detection of moment 

![screenshot_2015-01-26-14-00-34](https://cloud.githubusercontent.com/assets/250273/5911073/5047bd44-a576-11e4-8a78-d43af1522067.png)

**Comment by garvankeeley** [comment] 2015-01-27 00:22
Great info! I think there is a bug when the GPS is put to sleep we aren't setting the GPS to 0/0 in the main UI.
Did the "Location not changing" message disappear at all? I would have expected it to disappear for 2 mins, then re-appear. The Log screen will also show "is motionless: false" with a timestamp, when the app thinks you have moved (and the "Location not changing" message disappears).

**Comment by kbrosnan** [comment] 2015-01-27 00:26
To the best of my knowledge the "location not changing" message remains until the app is killed from the Samsung task killer or the phone is rebooted.

**Comment by Djfe** [comment] 2015-01-27 18:37
First: Pls make a screenshot of the log file, when the issue happens again, that helps us a lot with the debugging ;)

second:
One reason why it shows a different position is that you probably have Google's geo service activated -> OSM retrieves this position I think and shows it on the map although there is no gps fix

as @garvankeeley mentioned there is a bug that the GPS doesn't show 0/0 when the device is in paused mode (visible wifis and cells should be set to zero, too in my opinion because the device isn't scanning for them in paused mode)
I made a new issue for this #1436

**Comment by kbrosnan** [comment] 2015-01-27 19:19
The logs end up very similar to https://cloud.githubusercontent.com/assets/1011860/5393405/ccff1d00-8131-11e4-8d2d-bb74a7c6ad30.png which is already in this report.

**Comment by Djfe** [comment] 2015-01-27 21:54
@garvankeeley
why does it go into motionless mode within the second it records an observation?

**Comment by garvankeeley** [comment] 2015-01-28 15:33
I don't know what is happening here. I have an S5 on order, so I should be able to get this bug sorted

**Comment by grrrrr** [comment] 2015-01-28 17:40
I would just like to update that my issue mention on the S4 above is resolved,  embarrassingly it was due to `xprivacy` blocking `mozstumbler` access  to the phones sensors.

**Comment by garvankeeley** [comment] 2015-01-30 15:33
@kbrosnan I got an S5 (with android 4.4.2), and fresh out of the box, it reports it has a sig. motion sensor, and then doesn't trigger on sig. motion. Now to figure out how to handle this...

**Comment by Djfe** [comment] 2015-01-30 16:46
Good luck with that!
Maybe you can do it like crankycoder and use other apps to analyze what the sensor reports in general (especially with screen off)

**Comment by garvankeeley** [comment] 2015-02-03 17:24
To illustrate how broken the sensors are on the S5. This is the linear accelerometer at rest. It accelerates over time to faster than gravity. This wandering is 100% reproducible.

![u1gketmwnmdlaig6xasqbzugcpdz-5vsxet-1mh8vqm](https://cloud.githubusercontent.com/assets/5495083/6025308/5fc7d4dc-ab9f-11e4-9780-76e27b52cffc.png)

**Comment by Djfe** [comment] 2015-02-03 18:45
Have you considered letting your S5 get replaced?
You could argue with a hardware failure.
Just to see if all or only some S5s are affected.

What happens if you move?
Can you differentiate movement from this buggy behaviour?

**Comment by crankycoder** [comment] 2015-02-03 19:06
No, this is reproducible on multiple S5 instances.  It's a bug in the Samsung device or firmware.

**Closed as completed** 2015-03-17 18:29 UTC
Labels: bug
