### ISSUE TITLE
Period Wake to Scan

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1021] opened 2014-10-17 05:01 UTC
As a feature it would be nice of we could set Mozstumbler to wake once every 5, 10, 15, 30, 60, 120, 360 minutes and auto scan for a short interval of time.

It would also be nice if we could have periodic wake triggered by GPS calls from other apps or when charging.

Apps like Sensorly and OoenSignal do this as does Rootmetrics.

**Comment by Djfe** [comment] 2014-10-17 12:12
Duplicate of #369
Have you tried to give it some attention again? ^^
This feature will probably be implemented one day
You could ask @cascheberg whether he is interested in implementing it ;)
Garavankeeley and Cranky oder (core team) are occupied with the play store release atm.

**Comment by crankycoder** [comment] 2014-11-28 00:32
Closing  this as we've got code to hook the accelerometer to detect device motion.  Accelerometer use should be better than setting a fixed timer.

**Closed as completed by crankycoder** 2014-11-28 00:32 UTC
Labels: Power Consumption
