### ISSUE TITLE
Need cell and wifi scanning test mode

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#920] opened 2014-10-02 03:07 UTC
This is needed both for client and service testing. 

Service:
The service code paths can't be fully tested without simulating the wifi and cell scans, and it can't be load tested or analyzed in monitoring tools without actually scanning (which requires movement).

Client:
On the client side, I can use the KML feature (currently in PR) to load test the graphic display in the app.
I can't test MLS location lookups with this, as I am not saving the JSON bundles. 
I could expand the KML I/O to save out the scan data earlier than planned (rather than just saving the lat/long and wifi+cell counts as it does now). 

In general, a more complete simulation with movement will greatly aid development, if just for being able to run the app in android memory and performance profiling tools. It is very difficult to use these sitting a desk when the app is idle.

**Comment by crankycoder** [comment] 2014-11-07 18:32
Duplicate of #1191

**Closed as completed by crankycoder** 2014-11-07 18:32 UTC
