### ISSUE TITLE
Use no more than percent of battery

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#371] opened 2014-01-30 08:18 UTC
Once we have MozStumbler able to launch based on GPS activity we should also add a feature so that after a percentage of battery is used it no longer scans.

**Comment by cpeterso** [comment] 2014-01-30 08:22
@bkerensa: do you mean stop launching MozStumbler based on GPS activity when the battery is low? We do already have a low battery check to automatically disable scanning:

https://github.com/mozilla/MozStumbler/blob/ebd7a2ae5d62bab782d3d9d49bc2a2d3f948cbd1/src/org/mozilla/mozstumbler/ScannerService.java#L170

**Comment by ghost** [comment] 2014-01-30 08:52
No so I mean letting users define after MozStumbler consumers a certain percentage for it to disable scanning. Like I could set that MozStumbler can use no more than 10% of battery per day.

Apps like OpenSignal and Sensorly have this feature :)

**Comment by alebcay** [comment] 2014-02-05 01:48
Would appreciate that. MozStumbler drained my battery dry **while it was charging on A/C power**. Even after uninstall, my phone has lost it's full recharging potential - something is still eating away it's battery.

**Comment by cpeterso** [comment] 2014-02-19 22:22
I think this is a duplicate of issue #353.

**Closed as completed by cpeterso** 2014-02-19 22:22 UTC
Labels: enhancement
