### ISSUE TITLE
Scanning for cells stops working with the screen off

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1447] opened 2015-01-30 17:29 UTC
It could be a Rom dependent bug. But for some reason my phone seems to report 0 cells back after some time with the screen off. At least mozstumbler shows an only wifi report on the map then.
This is very unlikely because I only sat in a train, which drove through a bigger city and my carrier/provider is the German Telekom though (biggest provider around here) 
I guess cell scanning isn't triggered correctly.

Are others experiencing this as well?
The issue doesn't happen when the screen is on.

Motion detection is off and uploading is only allowed over wifi. (maybe uploading over mobile network would have woken up the baseband again, I'm going to test that)

**Comment by Djfe** [comment] 2015-02-13 20:16
Some screenshots that show my issue:

![2015-01-30 17 15 22](https://cloud.githubusercontent.com/assets/5685512/6194527/8aea6124-b3c5-11e4-96c9-f2840989d357.png)
![2015-02-01 18 32 12](https://cloud.githubusercontent.com/assets/5685512/6194529/8df5c2b4-b3c5-11e4-99b6-45e52f74980d.png)

**Comment by Djfe** [comment] 2015-02-25 09:28
![2015-02-21 04 47 46](https://cloud.githubusercontent.com/assets/5685512/6367998/d39924a2-bcd8-11e4-8d50-bd84f084fdea.png)

I drove on the highway for quite some time actually (the distance without cells is about 300kms)

on the way back I plugged in the charging cable and left the display on -> scanning was normal and cells got detected

**Comment by garvankeeley** [comment] 2015-02-25 22:42
This is a good bug for anyone who can reproduce with their device. I am happy to help on it, I can't repro it on my devices.

**Comment by Djfe** [comment] 2015-02-25 22:56
The thing is: your device needs to have it's screen off for at least 20min I guess, probably more, but not more than 45min/1hour

I will ask my rom developer if it could be a rom bug

EDIT:
anyways thx for taking your time trying to reproduce this bug ;)

my comment at xda:
http://forum.xda-developers.com/showthread.php?t=2575425&page=116#post59088125

**Comment by crankycoder** [comment] 2015-03-17 18:32
We haven't had anyone report this since the new motion sensor code has landed in v1.6 and v1.7 series.

**Closed as completed by crankycoder** 2015-03-17 18:32 UTC
Labels: Good first bug

**Comment by Djfe** [comment] 2015-03-18 02:18
Pls reopen, it is likely to be device specific but this happened to me in 1.6.x or something like that with the motion sensor related code turned OFF.
So it's something else.

Especially since it's only happening if the screen is turned off (so it couldn't be an issue with the motion detection anyways).

I think this bug has happened to me earlier as well (I was wondering in earlier reports why the number of cells stopped rising after some time with the screen off), but I couldn't visualize it like I can do now on the map

I wasn't able to see this issue in 1.7 yet because I would need to drive some time for it to happen
(will test it in a week or so with 1.7.7)

**Comment by crankycoder** [comment] 2015-03-18 02:36
Great. Let us know what you see in your tests.  The new motion detection code in 1.7 that did not exist in 1.6 should wake up if the network location listener indicates movement changed.

**Comment by Djfe** [comment] 2015-03-19 18:48
Lol I already said that the device had motion detection turned off arghh.

Also: Wifi points were visible (so the scanning was on), but the device didn't report any cells at all, which is the issue.

And yeah: I will check it soon and report back here ;)

**Comment by Djfe** [comment] 2015-04-02 21:26
I managed to reproduce this bug in 1.7.11 today but it was a little bit harder to notice because of #1611 

the log showed only wifi-only and empty reports (only gps coordinates) though

and what I also noticed when turning the device on:
my device had no mobile network/cell connection at all for a few seconds (the statusbar icon indicated it)
so it's save to say that it is device related

![2015-04-02 13 22 52](https://cloud.githubusercontent.com/assets/5685512/6974058/b28860ec-d98f-11e4-9acb-5f4678625e3c.png)
![2015-04-02 14 35 24](https://cloud.githubusercontent.com/assets/5685512/6974060/b4ead2ac-d98f-11e4-99f1-5e039010a860.png)
