### ISSUE TITLE
Bug: state of scanning button doesn't change

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/MozStumbler#746] opened 2014-08-01 16:06 UTC
My case with Version 0.21.0:
- GPS is deactivated
- Open MozStumbler
- Search location and close map
- Stop scanning is not possible, MozStumbler asked always for GPS settings

**Comment by Djfe** [comment] 2014-08-02 12:29
Something similar happens to me:
It stops scanning (notification disappears)
Though the button is still activated and it's caption is "stop scanning".

Maybe you should adjust the title of this issue, it's not very obvious from the title that you are talking about a bug.
"Bug: state of scanning button doesn't change"

**Comment by Gitschubser** [comment] 2014-08-02 13:52
Title is changed. Thank you. It describe the bug better.

**Comment by grrrrr** [comment] 2014-08-02 22:29
I see the following on 0.21.0 beta
- press `start`
- scanning starts and button changes to `stop`
- press `stop` and scanning stops but button does not change to `start`

You need to navigate away from `mozstumbler` and back again for the button to change back to `start`

**Comment by garvankeeley** [comment] 2014-08-03 15:21
Thanks, will get this fixed

**Comment by crankycoder** [comment] 2014-09-02 15:27
Pretty sure this is fixed in #782 - we should double check when that lands.

**Comment by crankycoder** [comment] 2014-09-16 15:38
Closing this as a duplicate of #782

**Closed as completed by crankycoder** 2014-09-16 15:38 UTC
Labels: bug
